Unhandled exception in internal background task 'check'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/pi/Desktop/Discord/cogs/canvas/calander.py", line 30, in check
    await channel.send(my_list)
  File "/usr/local/lib/python3.7/dist-packages/discord/abc.py", line 937, in send
    message_reference=reference)
  File "/usr/local/lib/python3.7/dist-packages/discord/http.py", line 247, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message
wait 15 seconds
Bot is ready
Rippy
CalebP
Task exception was never retrieved
future: <Task finished coro=<Loop._loop() done, defined at /usr/local/lib/python3.7/dist-packages/discord/ext/tasks/__init__.py:88> exception=HTTPException('400 Bad Request (error code: 50006): Cannot send an empty message')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/tasks/__init__.py", line 125, in _loop
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/pi/Desktop/Discord/cogs/canvas/calander.py", line 30, in check
    await channel.send(my_list)
  File "/usr/local/lib/python3.7/dist-packages/discord/abc.py", line 937, in send
    message_reference=reference)
  File "/usr/local/lib/python3.7/dist-packages/discord/http.py", line 247, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message
_ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_message coro=<bound method BotBase.on_message of <discord.ext.commands.bot.Bot object at 0xb67164f0>> exception=SystemExit(None)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/discord/client.py", line 708, in run
    loop.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/dist-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/bot.py", line 942, in on_message
    await self.process_commands(message)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/bot.py", line 939, in process_commands
    await self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/pi/Desktop/Discord/cogs/kill/off.py", line 15, in off
    exit()
  File "/usr/lib/python3.7/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None
